# Generated by Django 5.1.1 on 2024-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('author', models.TextField(max_length=100, verbose_name='author')),
                ('category', models.TextField(max_length=100, verbose_name='category')),
                ('publish_date', models.DateField(verbose_name='publish_date')),
                ('editorial', models.TextField(max_length=100, verbose_name='editorial')),
                ('pages', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='pages')),
                ('description', models.TextField(max_length=100, verbose_name='description')),
                ('files', models.FileField(upload_to='', verbose_name='files')),
                ('images', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='images')),
            ],
        ),
    ]
