# Generated by Django 5.1.1 on 2024-10-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.TextField(max_length=100, null=True, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='book',
            name='files',
            field=models.FileField(upload_to='pdfs', verbose_name='files'),
        ),
    ]
